plateaus_lottery_contract_address: "{some contract address}"
plateaus_node_validator_contract_address: "{some contract address}"
networks:
  - name: "polygon"
    min_amount: 0.1
    private_key: "{some private key}"
    lottery_validation_contract_address: "{some contract address}"
    rpc: "{some rpc}"
  - name: "zksync"
    min_amount: 0.001
    private_key: "{some private key}"
    lottery_validation_contract_address: "{some contract address}"
    rpc: "{some rpc}"
  - name: "scroll"
    min_amount: 0.001
    private_key: "{some private key}"
    lottery_validation_contract_address: "{some contract address}"
    rpc: "{some rpc}"
peer: "{some peer id}"
plateaus_private_key: "{some private key}"
plateaus_rpc: "https://plateaus-testnet.rhizom.me"
plateaus_rest: "http://sentry-nodes.rhizom.me:1317"
ipfs_token: "{some token}"