plateaus_lottery_contract_address: "{some contract address}"
polygon_lottery_validation_contract_address: "{some contract address}"
plateaus_node_validator_contract_address: "{some contract address}"
networks:
  - name: "polygon"
    min_amount: 0.1
  - name: "zksync"
    min_amount: 0.001
  - name: "scroll"
    min_amount: 0.001
peer: "{some peer id}"
plateaus_private_key: "{some private key}"
plateaus_rpc: "https://plateaus-testnet.rhizom.me"
polygon_private_key: "{some private key}"
polygon_rpc: "{some rpc}"
scroll_private_key: "{some private key}"
scroll_rpc: "{some rpc}"
zksync_private_key: "{some private key}"
zksync_rpc: "{some rpc}"
ipfs_token: "{some token}"